apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    deployment.kubernetes.io/revision: "2"
  creationTimestamp: "2021-11-27T03:41:44Z"
  generation: 3
  labels:
    app: datanode
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:labels:
              .: {}
              f:app: {}
          f:spec:
            f:containers:
              k:{"name":"hadoop-datanode-1"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"CORE_CONF_fs_defaultFS"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                  k:{"name":"CORE_CONF_hadoop_proxyuser_hue_groups"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"CORE_CONF_hadoop_proxyuser_hue_hosts"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"CORE_CONF_io_compression_codecs"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"HDFS_CONF_dfs_permissions_enabled"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"HDFS_CONF_dfs_webhdfs_enabled"}:
                    .: {}
                    f:name: {}
                    f:valueFrom:
                      .: {}
                      f:configMapKeyRef:
                        .: {}
                        f:key: {}
                        f:name: {}
                  k:{"name":"SERVICE_PRECONDITION"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
    manager: GoogleCloudConsole
    operation: Update
    time: "2021-11-27T03:43:41Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-11-27T03:43:45Z"
  name: datanode
  namespace: default
  resourceVersion: "1880316"
  uid: 2985c91a-8538-4890-8bf2-36099ccc49d7
spec:
  progressDeadlineSeconds: 600
  replicas: 2
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: datanode
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: datanode
    spec:
      containers:
      - env:
        - name: SERVICE_PRECONDITION
          value: namenode-4wqk8:9000
        - name: CORE_CONF_fs_defaultFS
          value: hdfs://namenode-4wqk8:9000
        - name: CORE_CONF_hadoop_proxyuser_hue_hosts
          valueFrom:
            configMapKeyRef:
              key: CORE_CONF_hadoop_proxyuser_hue_hosts
              name: datanode-config-e892
        - name: CORE_CONF_hadoop_proxyuser_hue_groups
          valueFrom:
            configMapKeyRef:
              key: CORE_CONF_hadoop_proxyuser_hue_groups
              name: datanode-config-e892
        - name: CORE_CONF_io_compression_codecs
          valueFrom:
            configMapKeyRef:
              key: CORE_CONF_io_compression_codecs
              name: datanode-config-e892
        - name: HDFS_CONF_dfs_webhdfs_enabled
          valueFrom:
            configMapKeyRef:
              key: HDFS_CONF_dfs_webhdfs_enabled
              name: datanode-config-e892
        - name: HDFS_CONF_dfs_permissions_enabled
          valueFrom:
            configMapKeyRef:
              key: HDFS_CONF_dfs_permissions_enabled
              name: datanode-config-e892
        - name: HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check
          valueFrom:
            configMapKeyRef:
              key: HDFS_CONF_dfs_namenode_datanode_registration_ip___hostname___check
              name: datanode-config-e892
        image: gcr.io/project-330303/walterdjs/hadoop-datanode:latest
        imagePullPolicy: Always
        name: hadoop-datanode-1
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status:
  availableReplicas: 2
  conditions:
  - lastTransitionTime: "2021-11-27T03:41:47Z"
    lastUpdateTime: "2021-11-27T03:41:47Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2021-11-27T03:41:44Z"
    lastUpdateTime: "2021-11-27T03:43:45Z"
    message: ReplicaSet "datanode-5fcbd7c557" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 3
  readyReplicas: 2
  replicas: 2
  updatedReplicas: 2

