apiVersion: v1
kind: Service
metadata:
  annotations:
    cloud.google.com/neg: '{"ingress":true}'
  creationTimestamp: "2021-11-27T03:15:20Z"
  finalizers:
  - service.kubernetes.io/load-balancer-cleanup
  generateName: namenode-
  labels:
    app: namenode
  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:generateName: {}
        f:labels:
          .: {}
          f:app: {}
      f:spec:
        f:externalTrafficPolicy: {}
        f:ports:
          .: {}
          k:{"port":9000,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
          k:{"port":9870,"protocol":"TCP"}:
            .: {}
            f:name: {}
            f:port: {}
            f:protocol: {}
            f:targetPort: {}
        f:selector:
          .: {}
          f:app: {}
        f:sessionAffinity: {}
        f:type: {}
    manager: GoogleCloudConsole
    operation: Update
    time: "2021-11-27T03:15:20Z"
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:finalizers:
          .: {}
          v:"service.kubernetes.io/load-balancer-cleanup": {}
      f:status:
        f:loadBalancer:
          f:ingress: {}
    manager: kube-controller-manager
    operation: Update
    time: "2021-11-27T03:15:51Z"
  name: namenode-4wqk8
  namespace: default
  resourceVersion: "1867735"
  uid: 940654b9-51d2-46dd-943d-614e21e8355a
spec:
  clusterIP: 10.52.14.225
  clusterIPs:
  - 10.52.14.225
  externalTrafficPolicy: Cluster
  ipFamilies:
  - IPv4
  ipFamilyPolicy: SingleStack
  ports:
  - name: 9870-to-9870-tcp
    nodePort: 32498
    port: 9870
    protocol: TCP
    targetPort: 9870
  - name: 9000-to-9000-tcp
    nodePort: 31759
    port: 9000
    protocol: TCP
    targetPort: 9000
  selector:
    app: namenode
  sessionAffinity: None
  type: LoadBalancer
status:
  loadBalancer:
    ingress:
    - ip: 34.132.61.108

